;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="State.Action.Attacking",DevComment="")
+GameplayTagList=(Tag="State.Action.Casting",DevComment="")
+GameplayTagList=(Tag="State.Action.JumpLanding",DevComment="")
+GameplayTagList=(Tag="State.Action.JumpLoop",DevComment="")
+GameplayTagList=(Tag="State.Action.MagicCasting",DevComment="")
+GameplayTagList=(Tag="State.Action.Rolling",DevComment="")
+GameplayTagList=(Tag="State.CC.Stun",DevComment="")
+GameplayTagList=(Tag="State.Cutscene",DevComment="")
+GameplayTagList=(Tag="State.Movement.Grounded",DevComment="")
+GameplayTagList=(Tag="State.Movement.InAir",DevComment="")
+GameplayTagList=(Tag="State.Stance.Combat",DevComment="")

